os:
  - linux

language: go

dist: trusty

go:
    - 1.9

env:
    - DEP_VERSION="0.4.1"

script:
    - set -e
# Run tests
    - go test github.com/cargurus/honeykaf/...
# Build binary and packages
    - go install -ldflags "-X main.BuildID=1.${TRAVIS_BUILD_NUMBER}" github.com/cargurus/honeykaf/...

before_install:
# Download the binary to bin folder in $GOPATH
    - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
# Make the binary executable
    - chmod +x $GOPATH/bin/dep
# Install fpm for deb/rpm package building
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential rpm

install:
    - true # HACK: fixes travis-CI lack of support for vendor/ + godeps
    - dep ensure

deploy:
    provider: releases
    file: honeykaf
    skip_cleanup: true
    on:
      repo: cargurus/honeykaf
      branch: master
      tags: true
